//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitap_mvc_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartitem
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Size { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<double> Total { get; set; }
        public string Url { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
